In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import MinMaxScaler

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

2023-04-05 22:02:42.669773: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
train = pd.read_csv('../datasets/goog_train.csv')

In [6]:
train.head(2)

Date    Open    High     Low   Close     Volume
0  1/3/2012  325.25  332.83  324.97  663.59  7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45  5,749,400

In [11]:
# train.iloc[:, 1] returns Series and .values -> 1D array
train.iloc[:, 1].values

array([325.25, 331.27, 329.83, ..., 793.7 , 783.33, 782.75])

In [12]:
# train.iloc[:, 1:2] returns df and .values -> 2D array
# same as
# train.iloc[:, [1]].values

train.iloc[:, 1:2].values

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [16]:
train = train.iloc[:, [1]].values

In [18]:
sc = MinMaxScaler()
train = sc.fit_transform(train)

In [19]:
train[:2]

array([[0.08581368],
       [0.09701243]])

In [21]:
train.max(), train.min()

(1.0, 0.0)